services:
  # api:
  #   build: .
  #   environment:
  #     POSTGRES_CONN_STR: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?sslmode=disable"
  #   depends_on:
  #     - database
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/product-service-projector

  database:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: