# Generated by Django 5.1.1 on 2024-09-23 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Continent",
            fields=[
                ("continentid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "continentname",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "db_table": "continents",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Countrie",
            fields=[
                ("countryid", models.AutoField(primary_key=True, serialize=False)),
                ("countryname", models.CharField(max_length=100)),
                ("flag_emoji", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "continentid",
                    models.ForeignKey(
                        blank=True,
                        db_column="continentid",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="admin_panel_diamap.continent",
                    ),
                ),
            ],
            options={
                "db_table": "countries",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Podcast",
            fields=[
                ("podcastid", models.AutoField(primary_key=True, serialize=False)),
                ("podcastname", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=20)),
                ("podcastdescription", models.TextField()),
                ("audioname", models.CharField(max_length=100)),
                (
                    "photoroute",
                    models.ImageField(blank=True, null=True, upload_to="photo/"),
                ),
                (
                    "audioroute",
                    models.FileField(blank=True, null=True, upload_to="audio/"),
                ),
                (
                    "countryid",
                    models.ForeignKey(
                        db_column="countryid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="admin_panel_diamap.countrie",
                    ),
                ),
            ],
            options={
                "db_table": "podcasts",
                "managed": True,
            },
        ),
    ]
